os:
  - linux
  - osx

dist: trusty
osx_image: xcode7.2

language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6-4.7-dev
      - clang-3.6

install:
  - wget https://gist.githubusercontent.com/dorentus/53545344d52ee0bc84f3/raw/swift-install -O swift-install
  - chmod +x swift-install

script:
  - ./swift-install DEVELOPMENT-SNAPSHOT-2016-02-25-a ./swift-dist
  - ./swift-dist/usr/bin/swift build
  - .build/debug/HelloWorld
